---
  - hosts: etcd
    any_errors_fatal: true
    name: "{{ play_name | default('Start Kubernetes Etcd Cluster') }}"
    serial: "{{ serial_count | default('100%') }}"
    become: yes
    vars_files:
      - group_vars/all.yaml
      - group_vars/etcd-k8s.yaml
      - group_vars/container_images.yaml
      
    pre_tasks:
      - name: download etcd image
        command: docker pull {{ images.etcd }}
        register: result
        until: result|succeeded
        retries: 2
        delay: 1

    roles:
      - role: etcd-backup
        when: upgrading is defined and upgrading|bool == true
      - etcd
