---
  - hosts: master[0]
    any_errors_fatal: true
    name: "Configure Heapster Cluster Monitoring"
    become: yes
    run_once: true
    vars_files:
      - group_vars/all.yaml
      - group_vars/container_images.yaml

    roles:
      - role: heapster