---
  - hosts: master
    any_errors_fatal: true
    name: "{{ play_name | default('Start Kubernetes Scheduler') }}"
    serial: "{{ serial_count | default('100%') }}"
    become: yes
    vars_files:
      - group_vars/all.yaml
      - group_vars/container_images.yaml

    pre_tasks:
      - name: download kube-scheduler image
        command: docker pull {{ images.kube_scheduler }}
        register: result
        until: result|succeeded
        retries: 2
        delay: 1

      - name: check if kube-scheduler service is active
        command: systemctl is-active -q kube-scheduler.service
        register: status
        failed_when: status.rc != 0 and status.rc != 3 # 0 = running, 3 = stopped/doesn't exist
        when: upgrading is defined and upgrading|bool == true

      - name: stop kube-scheduler service if running
        service:
          name: kube-scheduler.service
          state: stopped
          enabled: no
        when: upgrading is defined and upgrading|bool == true and status is defined and status.rc == 0
      - name: remove unnecessary kube-scheduler unit file
        file:
          path: "{{ init_system_dir }}/kube-scheduler.service"
          state: absent
        when: upgrading is defined and upgrading|bool == true

    roles:
      - kube-scheduler
