---
  - hosts: master:worker:ingress:storage
    any_errors_fatal: true
    name: "{{ play_name | default('Start Kubernetes Kubelet') }}"
    serial: "{{ serial_count | default('100%') }}"
    become: yes
    vars_files:
      - group_vars/all.yaml
      - group_vars/container_images.yaml

      
    roles:
      - role: packages-kubernetes
        when: allow_package_installation|bool == true
      - kubelet
