---
  - hosts: master
    any_errors_fatal: true
    name: "{{ play_name | default('Start Kubernetes Controller Manager') }}"
    serial: "{{ serial_count | default('100%') }}"
    become: yes
    vars_files:
      - group_vars/all.yaml
      - group_vars/container_images.yaml

    pre_tasks:
      - name: download kube-controller-manager image
        command: docker pull {{ images.kube_controller_manager }}
        register: result
        until: result|succeeded
        retries: 2
        delay: 1

    roles:
      - kube-controller-manager
