---
  - hosts: all
    any_errors_fatal: true
    name: "{{ play_name | default('Configure ntp in all nodes') }}"
    serial: "{{ serial_count | default('100%') }}"
    become: yes
    vars_files:
      - group_vars/all.yaml

    roles:
      - ntp
