---
  - hosts: master[0]
    any_errors_fatal: true
    name: "Delete Kubernetes Persistent Volume"
    become: yes
    vars_files:
      - group_vars/all.yaml

    tasks:
      - name: delete Kubernetes PV
        command: kubectl --kubeconfig {{ kubernetes_kubeconfig.kubectl }} --ignore-not-found=true delete pv {{ volume_name }}