---
  - hosts: all
    any_errors_fatal: true
    name: Run Cluster Pre-Flight Checks
    become: yes
    vars_files:
      - group_vars/all.yaml
    roles:
      - preflight
    environment: "{{proxy_env}}"
