---
  - hosts: master[0]
    any_errors_fatal: true
    name: "{{ play_name | default('Start Kubernetes Pod Rescheduler') }}"
    become: yes
    vars_files:
      - group_vars/all.yaml
      - group_vars/container_images.yaml

    roles:
      - rescheduler
