---
  - hosts: master
    any_errors_fatal: true
    name: Smoke Test Master Node
    become: yes
    serial: 1
    vars_files:
      - group_vars/all.yaml
      - group_vars/container_images.yaml

    roles:
      - smoketest
