---
  - hosts: storage
    any_errors_fatal: true
    name: "Bootstrap Persistent Storage Cluster"
    become: yes
    
    roles:
      - role: packages-glusterfs
        when: allow_package_installation|bool == true
      - glusterfs

  - hosts: storage
    any_errors_fatal: true
    name: "Create NFS service on the cluster"
    run_once: true
    become: yes
    vars_files:
      - group_vars/all.yaml
      - group_vars/container_images.yaml
    roles:
      - glusterfs-k8s
