---
  - hosts: master:worker:ingress:storage
    any_errors_fatal: true
    name: "{{ play_name | default('Start Weave Network Components') }}"
    serial: "{{ serial_count | default('100%') }}"
    become: yes
    vars_files:
      - group_vars/all.yaml
      - group_vars/container_images.yaml

    pre_tasks:
      - name: download networking images
        command: docker pull {{ item }}
        with_items:
          - "{{ images.weave }}"
          - "{{ images.weave_npc }}"
        register: result
        until: result|succeeded
        retries: 2
        delay: 1

    roles:
      - weave
