---
  - hosts: master:worker:ingress:storage
    any_errors_fatal: true
    name: "{{ play_name | default('Validate Weave Network Components') }}"
    serial: "{{ serial_count | default('100%') }}"
    become: yes
    vars_files:
      - group_vars/all.yaml

    tasks:
      - name: get the name of the weave-net pod running on this node
        command: kubectl --kubeconfig {{ kubernetes_kubeconfig.kubectl }} get pods -l=k8s-app=weave-net --template {%raw%}'{{range .items}}{{if eq .spec.nodeName{%endraw%} "{{ inventory_hostname|lower }}"{%raw%}}}{{.metadata.name}}{{"\n"}}{{end}}{{end}}'{%endraw%} -n kube-system
        register: pod_name
        until: pod_name is defined and pod_name.stdout is defined and pod_name.stdout != ""
        retries: 20
        delay: 6

      - name: wait until pod is in "Running" state
        command: kubectl --kubeconfig {{ kubernetes_kubeconfig.kubectl }} get pods {{ pod_name.stdout }} -o=jsonpath='{.status.phase}' -n kube-system
        register: readyPods
        until: readyPods.stdout == "Running"
        retries: 20
        delay: 6
