---
  - include: _calico-network-policy.yaml play_name="Upgrade Network Policy Controller" upgrading=true
    when: cni.enabled|bool == true and cni.provider == "calico"
  - include: _cluster-dns.yaml play_name="Upgrade Kubernetes DNS" upgrading=true
    when: dns.enabled|bool == true
  - include: _nginx-ingress.yaml play_name="Upgrade Kubernetes Ingress" upgrading=true
    when: configure_ingress|bool == true
  - include: _heapster.yaml play_name="Upgrade Heapster Cluster Monitoring" upgrading=true
    when: heapster.enabled|bool == true
  - include: _metrics-server.yaml play_name="Upgrade Kubernetes Metrics Server" upgrading=true
    when: metricsserver.enabled|bool == true
  - include: _kube-dashboard.yaml play_name="Upgrade Kubernetes Dashboard" upgrading=true
    when: dashboard.enabled|bool == true
  - include: _helm.yaml play_name="Upgrade Helm and Tiller" upgrading=true
    when: helm.enabled|bool == true
