apiVersion: v1
kind: Pod
metadata:
  labels:
    tier: control-plane
    component: kube-scheduler
    k8s-app: kube-scheduler
    kismatic/host: {{ inventory_hostname }}
  annotations:
    version: "{{ official_images.kube_apiserver.version }}"
    kismatic/version: "{{ kismatic_short_version }}"
  name: kube-scheduler
  namespace: kube-system
spec:
  hostNetwork: true
  containers:
  - name: kube-scheduler
    image: {{ images.kube_scheduler }}
    imagePullPolicy: IfNotPresent
    command:
      - kube-scheduler
{% set combined_options = kube_scheduler_option_defaults | combine(kube_scheduler_option_overrides) -%}
{% for option in combined_options | dictsort %}
{% if option[1] is defined and option[1] | string | length > 0 %}
      - "--{{ option[0] }}={{ option[1] }}"
{% endif %}
{% endfor %}
    volumeMounts:
      - mountPath: "{{ kubernetes_kubeconfig.scheduler }}"
        name: "kubeconfig"
        readOnly: true
      - mountPath: /etc/kubernetes
        name: ssl-certs-kubernetes
        readOnly: true
    livenessProbe:
      httpGet:
        host: 127.0.0.1
        path: /healthz
        port: 10251
      initialDelaySeconds: 15
      timeoutSeconds: 15
      failureThreshold: 8
  volumes:
    - name: "kubeconfig"
      hostPath:
        path: "{{ kubernetes_kubeconfig.scheduler }}"
    - hostPath:
        path: /etc/kubernetes
      name: ssl-certs-kubernetes
