---
  # setup directories
  - name: create directory
    file:
      path: "{{ etcd_install_dir }}"
      state: directory
  
  - name: copy CA certificate
    copy:
      src: "{{ tls_directory }}/ca.pem"
      dest: "{{ etcd_certificates.ca }}"
      owner: "{{ etcd_certificates.owner }}"
      group: "{{ etcd_certificates.group }}"
      mode: "{{ etcd_certificates.mode }}"
  
  - name: copy etcd server certificate and key
    copy:
      src: "{{ tls_directory }}/{{ item.src }}"
      dest: "{{ item.dest }}"
      owner: "{{ etcd_certificates.owner }}"
      group: "{{ etcd_certificates.group }}"
      mode: "{{ etcd_certificates.mode }}"
    when: "'etcd' in group_names"
    with_items:
      - {'src': "{{ inventory_hostname }}-etcd.pem", dest: "{{ etcd_certificates.etcd }}"}
      - {'src': "{{ inventory_hostname }}-etcd-key.pem", dest: "{{ etcd_certificates.etcd_key }}"}
      - {'src': "etcd-client.pem", dest: "{{ etcd_certificates.etcd_client }}"}
      - {'src': "etcd-client-key.pem", dest: "{{ etcd_certificates.etcd_client_key }}"}
