apiVersion: v1
kind: Pod
metadata:
  labels:
    tier: control-plane
    component: kube-controller-manager
    k8s-app: kube-controller-manager
    kismatic/host: {{ inventory_hostname }}
  annotations:
    version: "{{ official_images.kube_apiserver.version }}"
    kismatic/version: "{{ kismatic_short_version }}"
  name: kube-controller-manager
  namespace: kube-system
spec:
  hostNetwork: true
  containers:
  - name: kube-controller-manager
    image: {{ images.kube_controller_manager }}
    imagePullPolicy: IfNotPresent
    command:
      - kube-controller-manager
{% set combined_options = kube_controller_manager_option_defaults | combine(kube_controller_manager_option_overrides) -%}
{% for option in combined_options | dictsort %}
{% if option[1] is defined and option[1] | string | length > 0 %}
      - "--{{ option[0] }}={{ option[1] }}"
{% endif %}
{% endfor %}
    livenessProbe:
      httpGet:
        host: 127.0.0.1
        path: /healthz
        port: 10252
      initialDelaySeconds: 15
      timeoutSeconds: 15
      failureThreshold: 8
    volumeMounts:
    - mountPath: "{{ kubernetes_kubeconfig.controller_manager }}"
      name: "kubeconfig"
      readOnly: true
    - mountPath: /etc/kubernetes
      name: ssl-certs-kubernetes
      readOnly: true
    - mountPath: /etc/ssl/certs
      name: ssl-certs-host
      readOnly: true
    - name: usr-ca-certs-host
      mountPath: /usr/share/ca-certificates
      readOnly: true
{% if cloud_provider is defined and cloud_provider == 'aws' and ansible_os_family == 'RedHat' %}
    - mountPath: /etc/ssl/certs/ca-bundle.crt
      name: rhel-ca-bundle
      readOnly: true
{% endif %}
  volumes:
  - name: "kubeconfig"
    hostPath:
      path: "{{ kubernetes_kubeconfig.controller_manager }}"
  - hostPath:
      path: /etc/kubernetes
    name: ssl-certs-kubernetes
  - hostPath:
      path: /etc/ssl/certs/
    name: ssl-certs-host
  - hostPath:
      path: /usr/share/ca-certificates
    name: usr-ca-certs-host
{% if cloud_provider is defined and cloud_provider == 'aws' and ansible_os_family == 'RedHat' %}
  - hostPath:
      path: /etc/ssl/certs/ca-bundle.crt
    name: rhel-ca-bundle
{% endif %}
