---
  # setup directories
  - name: create {{ kubernetes_auth_dir }} directory
    file:
      path: "{{ kubernetes_auth_dir }}"
      state: directory

  - name: copy basicauth.csv to remote
    template:
      src: basicauth.csv
      dest: "{{ kubernetes_auth_dir }}/basicauth.csv"
      force: no
  - name: copy authorization-policy.json to remote
    copy:
      src: authorization-policy.json
      dest: "{{ kubernetes_auth_dir }}/authorization-policy.json"
      force: no
