---
  kind: Service
  apiVersion: v1
  metadata:
    name: kismatic-storage
    namespace: kube-system
  spec:
    selector:
      app: gluster-healthz
    ports:
      - name: rpcbind
        port: 111
      - name: nfs
        port: 2049
      - name: gluster-nfs-38465
        port: 38465
      - name: gluster-nfs-38466
        port: 38466
      - name: gluster-nfs-38468
        port: 38468
      - name: gluster-nfs-38469
        port: 38469
