kind: PersistentVolumeClaim
apiVersion: v1
metadata:
 name: jenkins-pvc
 namespace: cicd
spec:
 accessModes:
    - ReadWriteOnce
 resources:
   requests:
     storage: 20Gi
# storageClassName: ceph-web
