---
  # Setup certs for Docker registry
  # To use self-signed certs modify /etc/docker/certs.d/$master[0]:$PORT/ca.crt
  # ca.crt is just renamed ca.pem

  # setup directories
  - name: create {{ docker_install_dir }}
    file:
      path: "{{ docker_install_dir }}"
      state: directory
  - name: create directory for certificates
    file:
      path: "{{ docker_self_signed_cert_dir }}"
      state: directory

  # copy ca
  - name: copy {{ docker_certificates_ca_file_name }}
    copy:
      src: "{{ docker_certificates_ca_path }}"
      dest: "{{ docker_self_signed_cert_dir }}/ca.crt"
      owner: "{{ docker_certificates_owner }}"
      group: "{{ docker_certificates_group }}"
      mode: "{{ docker_certificate_mode }}"
    when: docker_certificates_ca_path is defined and docker_certificates_ca_path != ""

  # copy ca twice, only on rhel74
  - name: copy to  {{ docker_certificates_ca_file_name }}
    copy:
      src: "{{ docker_certificates_ca_path }}"
      dest: "/etc/pki/ca-trust/source/anchors/ca1.crt"
      owner: "{{ docker_certificates_owner }}"
      group: "{{ docker_certificates_group }}"
      mode: "{{ docker_certificate_mode }}"
    when: docker_certificates_ca_path is defined and docker_certificates_ca_path != "" and ansible_os_family == 'RedHat'

  # update the cat, only on rhel74
  - name: update ca
    shell: update-ca-trust
    when: ansible_os_family == 'RedHat'
