---
  - name: install glusterfs yum package
    yum:
      name: glusterfs-server-{{glusterfs_server_version_rhel}}
      state: present
      disable_gpg_check: yes    # does not work on RHEL
    register: glusterfs_rpm
    until: glusterfs_rpm|success
    retries: 3
    delay: 3
    when: ansible_os_family == 'RedHat'
    environment: "{{proxy_env}}"


  - name: install glusterfs deb package
    apt:
      name: glusterfs-server={{glusterfs_server_version_ubuntu}}
      state: present
    register: glusterfs_deb
    until: glusterfs_deb|success
    retries: 3
    delay: 3
    when: ansible_os_family == 'Debian'
    environment: "{{proxy_env}}"
