---
  - name: remove kubelet package
    package: name=kubelet state=absent
    when: "'master' in group_names or 'worker' in group_names or 'ingress' in group_names or 'storage' in group_names"
    register: result
    until: result|success
    retries: 2
    delay: 1

  - name: remove kubectl package
    package: name=kubectl state=absent
    when: "'master' in group_names or 'worker' in group_names or 'ingress' in group_names or 'storage' in group_names"
    register: result
    until: result|success
    retries: 2
    delay: 1

  - name: remove docker-engine package
    package: name=docker-engine state=absent
    when: "'master' in group_names or 'worker' in group_names or 'ingress' in group_names or 'storage' in group_names"
    register: result
    until: result|success
    retries: 2
    delay: 1

  - name: remove etcd package
    package: name=etcd state=absent
    when: "'etcd' in group_names"
    register: result
    until: result|success
    retries: 2
    delay: 1

  - name: remove Kismatic yum repository
    yum_repository:
      name: kismatic
      description: Kismatic Packages
      baseurl: "https://kismatic-packages-rpm.s3-accelerate.amazonaws.com"
      state: absent
    when: ansible_os_family == 'RedHat'

  - name: remove Kismatic deb repository
    apt_repository:
      repo: 'deb https://kismatic-packages-deb.s3-accelerate.amazonaws.com kismatic-xenial main'
      state: absent
    when: ansible_os_family == 'Debian'
  
  - name: remove outdated docker deb repository
    apt_repository:
      repo: 'deb https://apt.dockerproject.org/repo/ ubuntu-xenial main'
      state: absent
    when: ansible_os_family == 'Debian'