apiVersion: v1
kind: PersistentVolume
metadata:
  name: "{{ volume_name }}"
  annotations:
    volume.beta.kubernetes.io/storage-class: "{{ volume_storage_class }}"
spec:
  capacity:
    storage: {{ volume_quota_gb }}Gi
  accessModes:
{% for mode in volume_access_modes %}
    - {{ mode }}
{% endfor %}
  persistentVolumeReclaimPolicy: "{{ volume_reclaim_policy }}"
  nfs:
    path: /{{ volume_name }}
    server: {{ storage_cluster_ip }}
