---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: contiv-netmaster
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: contiv-netmaster
subjects:
- kind: ServiceAccount
  name: contiv-netmaster
  namespace: kube-system
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: contiv-netmaster
  namespace: kube-system
rules:
  - apiGroups:
    - ""
    - extensions
    resources:
      - pods
      - nodes
      - namespaces
      - networkpolicies
    verbs:
      - watch
      - list
      - update
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: contiv-netmaster
  namespace: kube-system
---
# This manifest deploys the Contiv API Server on Kubernetes.
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: contiv-netmaster
  namespace: kube-system
  labels:
    k8s-app: contiv-netmaster
spec:
  # The netmaster should have 1, 3, 5 nodes of which one is active at any given time.
  # More nodes are desired in a production environment for HA.
  template:
    metadata:
      name: contiv-netmaster
      namespace: kube-system
      labels:
        k8s-app: contiv-netmaster
      annotations:
        scheduler.alpha.kubernetes.io/critical-pod: ''
    spec:
      # The netmaster must run in the host network namespace so that
      # it isn't governed by policy that would prevent it from working.
      hostNetwork: true
      # Not using tolerations until we implement our taints/tolerations strategy.
      # tolerations:
      # - key: node-role.kubernetes.io/master
      #   effect: NoSchedule
      nodeSelector:
        node-role.kubernetes.io/master: ""
      serviceAccountName: contiv-netmaster
      containers:
        - name: contiv-netmaster
          image: "{{ images.contiv_netplugin }}"
          args:
            - -m
            - -pkubernetes
          env:
            - name: CONTIV_ETCD
              valueFrom:
                configMapKeyRef:
                  name: contiv-config
                  key: cluster_store
            - name: CONTIV_CONFIG
              valueFrom:
                configMapKeyRef:
                  name: contiv-config
                  key: config
          volumeMounts:
            - mountPath: /var/contiv
              name: var-contiv
              readOnly: false
        - name: contiv-api-proxy
          image: "{{ images.contiv_authproxy }}"
          args:
            - --tls-key-file=/var/contiv/certs/tls.key
            - --tls-certificate=/var/contiv/certs/tls.crt
            - --data-store-address=$(CONTIV_ETCD)
            - --netmaster-address=localhost:9999
          env:
            - name: NO_NETMASTER_STARTUP_CHECK
              value: "0"
            - name: CONTIV_ETCD
              valueFrom:
                configMapKeyRef:
                  name: contiv-config
                  key: cluster_store
          securityContext:
            privileged: false
          volumeMounts:
            - mountPath: /var/contiv
              name: var-contiv
              readOnly: false
            - mountPath: /var/contiv/certs
              name: contiv-certs
              readOnly: true
      volumes:
        # Used by contiv-netmaster
        - name: contiv-certs
          secret:
            secretName: "{{ contiv.proxy_server_certs_secret_name }}"
        - name: var-contiv
          hostPath:
            path: /var/contiv
